### ISSUE TITLE
Admin-Text-Field fixen

### ISSUE THREAD

**Issue by SaraLuethi** [71m024/pradmin#8]
Im user.form.jsx (also dort wo man neue User machen kann), in den Feldern ‘Email’ und ‘Passwort’ spinnt die Eingabe...
--> habe bereits einen branch (feature/changes) gemacht, auf dem ich den Regex gefixt habe, da der falsch war
- wenn man Nummern eingibt und dann einen Buchstaben, dann schreibt es den BS nicht
- wenn man Buchstaben eingibt und dann eine Zahl, dann macht es einen 'NaN' draus

**Comment by 71m024** [comment]
@SaraLuethi  Danke fürs fixen. Habe es auf main kopiert und mache grad noch einen neuen release.
